package com.gl.ceir.alerts.constants;

public enum AlertIds {

    CONFIGURATION_VALUE_MISSING, CONFIGURATION_VALUE_WRONG, DATABASE_EXCEPTION, DATABASE_TABLE_EXCEPTION, MODULE_EXECUTED_WITH_EXCEPTION, SMS_VALUE_MISSING, NOTIFICATION_SEND_EXCEPTION
    ,FILE_NOT_FOUND_EXCEPTION;
}
